### ISSUE TITLE
NAIP/Sentinel-2 joint training

### ISSUE THREAD

**Issue by mizoru** [allenai/satlas#22]
Were no models trained on the entirety of the dataset, that is both high-res and low-res images, and if so, why?

**Comment by favyen2** [comment]
Not on the final dataset. We found that models inputting both high-res and low-res images did not benefit from the low-res images since the 10x difference in resolution means they don't really provide any additional information (even though they do have a few more bands).

We may explore training with both Sentinel-1 and Sentinel-2 images though.
