### ISSUE TITLE
Suggest using S2MSI2A instead of S2MSI1C product type

### ISSUE THREAD

**Issue by rbavery** [allenai/satlas#42]
Hello, I would like to suggest using S2MSI2A next time around.

The S2MSI1C product wasn't atmospherically corrected, so images will have more artifacts from dust, clouds, etc. It's also only available in JPEG, so it makes modern imagery access patterns like partial image fetching and parallel chunk reading impossible. This is possible with the atmospherically corrected S2MSI2A product which is distributed in cloud optimized geotiff format by AWS and Azure.

https://element84.com/geospatial/introducing-earth-search-v1-new-datasets-now-available/ 

https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a

**Comment by favyen2** [comment]
Thanks for your comment. We decided to use L1C because the additional processing of L2A can introduce artifacts of its own, and we wanted the model to see reflectance values closest to the raw sensor values, since we believed the model could learn most of that processing. But we will keep this in mind for the future.
